development:
  adapter: postgresql
  encoding: utf8
  database: argument_development
  pool: 5
  username: murica
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: argument_test
  pool: 5
  username: murica
  password:
